language: generic
python: 2.7

matrix:
  include:
    - name: "Ubuntu 16.04 LTS without Ansible"
      os: linux
      dist: xenial
      sudo: required
    - name: "Ubuntu 16.04 LTS with Ansible 2.7 PyPI installed"
      os: linux
      dist: xenial
      sudo: required
      env: ANSIBLE_VERSION='<2.8.0'

branches:
  only:
    - master
    - develop
    - /^feature\/.*$/
    - /^bugfix\/.*$/
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

before_install:
  # Cleanup existing NVM installation
  - unset NVM_CD_FLAGS
  - unset NVM_DIR
  - unset NVM_BIN
  - rm -rf /home/travis/.nvm
  - rm -rf /etc/profile.d/travis-nvm.sh

install:
  # Install Ansible with pip on Ubuntu
  - >
    if [[ "$ANSIBLE_VERSION" != "" ]]; then
      pip install --user ansible${ANSIBLE_VERSION}
    fi

script:

  # Test setup script
  - ./setup -n

  # Check syntax of the Ansible playbooks
  - ./setup -s

  # Run playbooks without installing roles
  - ./setup -q

  # Run idempotence tests for each playbook
  - ./tests/idempotence
