language: generic
python: 2.7

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: linux
      dist: xenial
      sudo: required

before_install:
  # Cleanup existing NVM installation
  - unset NVM_CD_FLAGS
  - unset NVM_DIR
  - unset NVM_BIN
  - rm -rf /home/travis/.nvm
  - rm -rf /etc/profile.d/travis-nvm.sh

script:

  # Test setup script
  - ./setup -n

  # Check syntax of the Ansible playbooks
  - ./setup -s

  # Run playbooks without installing roles
  - ./setup -q

  # Run idempotence tests for each playbook
  - ./tests/idempotence
