# -*- mode: yaml -*-
# vim:ts=2:sw=2:ai:si:syntax=yaml
#
# Travis CI configuration
# https://docs.travis-ci.com/
---

# Run tests against pull requests and main branches only
if: |
  type = pull_request OR \
  branch IN (master, develop)

language: generic

matrix:
  include:
    - name: "Ubuntu 16.04 LTS without Ansible"
      os: linux
      dist: xenial
    - name: "Ubuntu 18.04 LTS without Ansible"
      os: linux
      dist: bionic
    - name: "Ubuntu 16.04 LTS with Ansible 2.7 PyPI installed"
      os: linux
      dist: xenial
      env: ANSIBLE_VERSION='<2.8.0'
    - name: "Ubuntu 16.04 LTS with Ansible 2.8 PyPI installed"
      os: linux
      dist: xenial
      env: ANSIBLE_VERSION='<2.9.0,!=2.8.6'

before_install:
  # Cleanup existing NVM installation
  - unset NVM_CD_FLAGS
  - unset NVM_DIR
  - unset NVM_BIN
  - rm -rf /home/travis/.nvm
  - rm -rf /etc/profile.d/travis-nvm.sh

install:
  # Install Ansible with pip on Ubuntu
  - >
    if [[ "$ANSIBLE_VERSION" != "" ]]; then
      pip install --user ansible${ANSIBLE_VERSION}
    fi

script:
  # Use Travis test configuration
  - cp machine.travis.yaml machine.yaml

  # Install roles
  - ./setup -n || travis_terminate 1

  # Check syntax of the Ansible playbooks
  - ./setup -s || travis_terminate 1

  # Run playbooks without installing roles
  - ./setup -q || travis_terminate 1

  # Avoid updating apt cache during idempotence tests
  - >
    echo "update_apt_cache: false" >> machine.yaml

  # Run idempotence tests
  - >
    ./setup -q \
      | grep -q 'changed=0.*failed=0' \
      && (echo 'Idempotence test: pass' && exit 0) \
      || (echo 'Idempotence test: fail' && exit 1)
