# -*- mode: yaml -*-
# vim:ts=2:sw=2:ai:si:syntax=yaml
#
# Ansible Galaxy roles to install
---

- name: markosamuli.asdf
  version: v1.0.0
- name: markosamuli.aws_tools
  version: v2.0.0
- name: markosamuli.gcloud
  version: v2.0.0
- name: markosamuli.golang
  src: https://github.com/markosamuli/ansible-golang
  version: v1.0.0
- name: markosamuli.hyper
  src: https://github.com/markosamuli/ansible-hyper
  version: v1.2.0
- name: markosamuli.nvm
  version: v1.3.0
- name: markosamuli.packer
  src: https://github.com/markosamuli/ansible-packer
  version: v1.0.0
- name: markosamuli.pyenv
  version: v2.0.0
- name: markosamuli.terraform
  version: v1.2.1
- name: markosamuli.vagrant
  src: https://github.com/markosamuli/ansible-vagrant
  version: v1.0.0
- name: markosamuli.linuxbrew
  version: v1.1.0
