---
- name: Load variables for the target system
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
    - "default.yml"

- name: Remove old versions of Docker
  apt:
    name:
      - docker
      - docker-engine
      - docker.io
    state: absent

- name: Remove conflicting packages
  apt:
    name:
      - containerd
      - runc
    state: absent

- name: Install dependencies
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common

- name: Add Google Cloud apt GPG key
  apt_key:
    url: "{{ gcloud_apt_key_url }}"

- name: Add Docker apt GPG key
  apt_key:
    id: "{{ docker_apt_key_id }}"
    url: "{{ docker_apt_key_url }}"

- name: Add Docker repository
  apt_repository:
    repo: "deb [arch=amd64] {{ docker_apt_url }} {{ docker_apt_release }} {{ docker_apt_channel }}"
    filename: docker
    mode: "0644"

- name: Install Docker CE
  apt:
    name: docker-ce

- name: Install Docker CE CLI
  apt:
    name: docker-ce-cli

- name: Install containerd.io
  apt:
    name: containerd.io
