---

- name: Remove tagplus5 Visual Studio Code PPA repository
  apt_repository:
    repo: 'deb https://tagplus5.github.io/vscode-ppa/ubuntu ./'
    state: absent

- name: Remove Visual Studio Code if installed via APT
  apt:
    package: code
    state: absent

- name: Check if vscode snap package exists
  stat:
    path: /snap/bin/vscode
  register: vscode_st
  changed_when: False

- name: Remove unmaintained vscode snap package
  command: snap remove vscode
  when: vscode_st.stat.exists

- name: Check if code snap package exists
  stat:
    path: /snap/bin/code
  register: code_st
  changed_when: False

- name: Install Visual Studio Code via code snap package
  command: snap install code --classic
  when: not code_st.stat.exists
