---
- name: Load variables for the target system
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "os/{{ ansible_distribution }}.yml"
        - "os/{{ ansible_os_family }}.yml"
      paths: vars

- name: Debian-based system
  include_tasks: Debian.yml
  when: ansible_os_family == 'Debian'
