---

- name: Check Linux requirements
  hosts: all
  tags:
    - always
    - linux
  tasks:
    - name: Check that we're running Linux
      assert:
        that:
          - "ansible_system == 'Linux'"
        msg: "This playbook only supports Linux systems"

    - name: Check that we're running supported Debian-based distribution
      assert:
        that:
          - "ansible_distribution == 'Ubuntu'
             or ansible_distribution == 'Pengwin'"
        msg: "This playbook only supports Ubuntu and Pengwin distributions"

    - name: Update APT package cache
      become: true
      apt:
        update_cache: true
