---

- name: Detect Windows Subsystem for Linux
  hosts: all
  tags:
    - always
    - wsl
  tasks:

    - name: Detect Windows Subsystem for Linux
      command: "sh -c 'grep -q Microsoft /proc/version && echo yes || echo no'"
      register: detect_wsl_grep
      changed_when: False

    - name: Set Windows Subsystem for Linux fact
      set_fact:
        is_wsl: "{{ detect_wsl_grep.stdout | bool }}"
