---

- name: Check if .bash_profile exists
  stat:
    path: "{{ bash_home }}/.bash_profile"
  register: bash_profile_st

- name: Check whether ~/.bashrc is loaded from ~/.bash_profile
  command: grep -Fxq "source ~/.bashrc" {{ bash_home }}/.bash_profile
  register: check_bashrc
  ignore_errors: yes
  changed_when: no
  when: bash_profile_st.stat.exists

- name: Ensure ~/.bashrc exists
  file:
    path: "{{ bash_home }}/.bashrc"
    state: touch
  when: bash_profile_st.stat.exists

- name: Load ~/.bashrc from ~/.bash_profile
  blockinfile:
    dest: "{{ bash_home }}/.bash_profile"
    block: |
      if [ -f ~/.bashrc ]; then
        source ~/.bashrc
      fi
  when: bash_profile_st.stat.exists and check_bashrc.rc != 0
