---
# tasks file for markosamuli.hyper

- name: Load variables for the target system
  include_vars: "{{ item }}"
  with_first_found:
    - "os/{{ ansible_distribution }}/{{ ansible_distribution_release }}.yml"
    - "os/{{ ansible_distribution }}.yml"

- name: Load variables for WSL systems
  include_vars: "wsl.yml"
  when: is_wsl | default(false)

- name: Install using APT
  include_tasks: install_apt.yml
  when: ansible_os_family == 'Debian'

- name: Create custom.prf file
  become: true
  template:
    dest: /etc/lynis/custom.prf
    src: "custom.prf.j2"
    owner: root
    group: root
    mode: "0644"
