---

- name: Remove conflicting Hashicorp installations
  hosts: all
  tags:
  - hashicorp
  tasks:
  - name: Remove /usr/bin/terraform binary
    file:
      path: /usr/bin/terraform
      state: absent
    tags: terraform
  - name: Remove /usr/bin/packer binary
    file:
      path: /usr/bin/packer
      state: absent
    tags: packer

- name: Install Hashicorp tools
  hosts: all
  tags:
  - hashicorp
  roles:
  - role: markosamuli.terraform
    tags: terraform
  - role: markosamuli.packer
    tags: packer
