---

- name: Remove conflicting Terraform installations
  hosts: all
  tags:
  - hashicorp
  - terraform
  tasks:

  - name: Check if Terraform is installed with asdf
    stat:
      path: /home/markosamuli/.asdf/installs/terraform
    register: asdf_terraform_install

  - name: Remove /usr/bin/terraform binary
    file:
      path: /usr/bin/terraform
      state: absent

  - name: Remove /usr/local/bin/terraform binary
    file:
      path: /usr/local/bin/terraform
      state: absent
    when: asdf_terraform_install.stat.exists

  - name: Remove /opt/terraform directory
    file:
      path: /opt/terraform
      state: absent
    when: asdf_terraform_install.stat.exists

- name: Remove conflicting Packer installations
  hosts: all
  tags:
  - hashicorp
  - packer
  tasks:

  - name: Check if Packer is installed with asdf
    stat:
      path: /home/markosamuli/.asdf/installs/packer
    register: asdf_packer_install

  - name: Remove /usr/bin/packer binary
    file:
      path: /usr/bin/packer
      state: absent

  - name: Remove /usr/local/bin/packer binary
    file:
      path: /usr/local/bin/packer
      state: absent
    when: asdf_packer_install.stat.exists

  - name: Remove /opt/packer directory
    file:
      path: /opt/packer
      state: absent
    when: asdf_packer_install.stat.exists

- name: Install Hashicorp tools if not installed with asdf
  hosts: all
  tags:
  - hashicorp
  roles:

  - role: markosamuli.terraform
    tags: terraform
    when: not asdf_terraform_install.stat.exists

  - role: markosamuli.packer
    tags: packer
    when: not asdf_packer_install.stat.exists
