---

- name: Setup variables and check requirements
  hosts: all
  tasks:

    - name: Check that we're running macOS
      assert:
        that:
          - "ansible_os_family == 'Darwin'"
        msg: "This playbook only supports macOS systems"
