---

- import_playbook: setup.yml

- import_playbook: linuxbrew.yml
  when: install_linuxbrew | bool

- import_playbook: terminals.yml
  when: not is_wsl

- import_playbook: slack.yml
  when: install_slack | bool

- import_playbook: tools.yml

- import_playbook: vim.yml
- import_playbook: neovim.yml
- import_playbook: vscode.yml

- import_playbook: git.yml

- import_playbook: asdf.yml
  when: install_asdf | bool

- import_playbook: nodejs.yml
  when: install_nodejs | bool

- import_playbook: python.yml
  when: install_python | bool

- import_playbook: golang.yml
  when: install_golang | bool

- import_playbook: ruby.yml
  when: install_ruby | bool

- import_playbook: vagrant.yml
  when: install_vagrant | bool

- import_playbook: docker.yml
  when: install_docker | bool

- import_playbook: gcloud.yml
- import_playbook: aws.yml

- import_playbook: terraform.yml
  when: install_terraform | bool

- import_playbook: packer.yml
  when: install_packer | bool

- import_playbook: permissions.yml
