---

- import_playbook: setup.yml

- import_playbook: terminals.yml
  when: not is_wsl

- import_playbook: tools.yml

- import_playbook: vim.yml
- import_playbook: neovim.yml

- import_playbook: vscode.yml
  when: not is_wsl

- import_playbook: git.yml
- import_playbook: asdf.yml

- import_playbook: nodejs.yml
- import_playbook: python.yml
- import_playbook: golang.yml

- import_playbook: vagrant.yml
  when: not is_wsl

- import_playbook: docker.yml
  when: not is_wsl

- import_playbook: gcloud.yml
- import_playbook: aws.yml

- import_playbook: packer.yml
- import_playbook: terraform.yml
