---

- import_playbook: setup/linux.yml

- import_playbook: setup/wsl.yml
  when: is_wsl is undefined

- import_playbook: setup/ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- import_playbook: setup/pengwin.yml
  when: ansible_distribution == 'Pengwin'

- import_playbook: terminals.yml
  when: not is_wsl

- import_playbook: tools.yml
- import_playbook: editors.yml
- import_playbook: git.yml
- import_playbook: asdf.yml

- import_playbook: nodejs.yml
- import_playbook: python.yml

- import_playbook: vagrant.yml
  when: not is_wsl

- import_playbook: docker.yml
  when: not is_wsl

- import_playbook: gcloud.yml
- import_playbook: aws.yml
- import_playbook: packer.yml
- import_playbook: terraform.yml
- import_playbook: golang.yml
