---

- import_playbook: linux.yml

- import_playbook: wsl.yml
  when: is_wsl is undefined

- import_playbook: ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- import_playbook: pengwin.yml
  when: ansible_distribution == 'Pengwin'

- import_playbook: terminals.yml
  when: not is_wsl

- import_playbook: tools.yml
- import_playbook: editors.yml
- import_playbook: git.yml
- import_playbook: front-end-toolkit.yml
- import_playbook: python.yml

- import_playbook: vagrant.yml
  when: not is_wsl

- import_playbook: docker.yml
  when: not is_wsl

- import_playbook: gcloud.yml
- import_playbook: aws.yml
- import_playbook: hashicorp.yml
- import_playbook: golang.yml
