---

- name: Remove conflicting Packer installations
  hosts: all
  tags: packer
  tasks:

    - name: Check if asdf is installed
      stat:
        path: "{{ ansible_env.HOME }}/.asdf"
      register: asdf_st
      become: false

    - name: Check if Packer is installed with asdf
      stat:
        path: "{{ ansible_env.HOME }}/.asdf/installs/packer"
      register: asdf_packer_install
      when: asdf_st.stat.exists
      become: false

    - name: Remove /usr/bin/packer binary
      file:
        path: /usr/bin/packer
        state: absent

    - name: Remove /usr/local/bin/packer binary
      file:
        path: /usr/local/bin/packer
        state: absent
      when: asdf_packer_install.stat.exists

    - name: Remove /opt/packer directory
      file:
        path: /opt/packer
        state: absent
      when: asdf_packer_install.stat.exists

- name: Install Packer if not installed with asdf
  hosts: all
  tags: packer
  roles:
    - role: markosamuli.packer
      when: not asdf_packer_install.stat.exists
