---
- name: Python
  hosts: all
  tags: python
  tasks:
    - name: Install Python
      package:
        name: python

    - name: Install pip
      package:
        name: python-pip

    - name: Install virtualenv
      pip:
        name: virtualenv

- name: Python version management
  hosts: all
  become: false
  tags: pyenv
  roles:
    - role: markosamuli.pyenv
