---

- name: Python
  hosts: all
  tasks:

  - name: Install Python
    package:
      name: python

  - name: Install pip
    package:
      name: python-pip

  - name: Install virtualenv
    pip:
      name: virtualenv
