---
- name: Security hardening
  hosts: all
  tags: security-hardening
  tasks:
    - name: Install USBGuard
      when: not is_wsl | bool
      apt:
        name: usbguard

    - name: Install passwdqc - password/passphrase strength checking and enforcement
      apt:
        name:
          - passwdqc
          - libpam-passwdqc

    - name: Install debsums
      apt:
        name: debsums
