---
- name: Remove conflicting Terraform system installations
  hosts: all
  tags: terraform
  become: true
  tasks:
    - name: Remove /usr/bin/terraform binary
      file:
        path: /usr/bin/terraform
        state: absent

    - name: Remove /opt/terraform directory
      file:
        path: /opt/terraform
        state: absent

- name: Remove conflicting Terraform user installations
  hosts: all
  tags: terraform
  become: false
  tasks:
    - name: Remove Terraform asdf plugin
      file:
        path: "{{ ansible_env.HOME }}/.asdf/plugins/terraform"
        state: absent

    - name: Remove Terraform asdf installation
      file:
        path: "{{ ansible_env.HOME }}/.asdf/installs/terraform"
        state: absent

    - name: Remove Terraform asdf shim
      file:
        path: "{{ ansible_env.HOME }}/.asdf/shims/terraform"
        state: absent

- name: Install Terraform
  hosts: all
  tags: terraform
  become: false
  roles:
    - role: tfenv
