---
- name: Remove conflicting Terraform installations
  hosts: all
  tags: terraform
  tasks:
    - name: Set asdf installs directory
      set_fact:
        asdf_installs_dir: "{{ user_home }}/.asdf/installs"

    - name: Check if Terraform is installed with asdf
      stat:
        path: "{{ asdf_installs_dir }}/terraform"
      register: asdf_terraform_install
      become: false

    - name: Remove /usr/bin/terraform binary
      file:
        path: /usr/bin/terraform
        state: absent

    - name: Remove /usr/local/bin/terraform binary
      file:
        path: /usr/local/bin/terraform
        state: absent
      when: asdf_terraform_install.stat.exists

    - name: Remove /opt/terraform directory
      file:
        path: /opt/terraform
        state: absent
      when: asdf_terraform_install.stat.exists

- name: Install Terraform if not installed with asdf
  hosts: all
  tags: terraform
  roles:
    - role: markosamuli.terraform
      when: not asdf_terraform_install.stat.exists
