---
- name: Tools
  hosts: all
  tags: tools
  tasks:
    - name: Install GNU make
      package:
        name: make

    - name: Install wget
      package:
        name: wget

    - name: Install cURL
      package:
        name: curl

    - name: Install jq command-line JSON processor
      package:
        name: jq

    - name: Install The Silver Searcher code searching utility
      apt:
        name: silversearcher-ag

    - name: Install htop
      package:
        name: htop

    - name: Install pass (password manager)
      package:
        name: pass

    - name: Install asciinema
      package:
        name: asciinema

    - name: Install ncdu (disk usage analyzer)
      package:
        name: ncdu

    - name: Install fd (alternative to find)
      apt:
        deb: https://github.com/sharkdp/fd/releases/download/v8.1.1/fd_8.1.1_amd64.deb

    - name: Install fzf (command-line fuzzy finder)
      package:
        name: fzf
      when: |
        (ansible_distribution == 'Ubuntu' and ansible_distribution_version|int >= 20)
        or (ansible_distribution == 'Debian' and ansible_distribution_version|int >= 10)

    - name: Install ripgrep (search tool)
      package:
        name: ripgrep
      when: |
        (ansible_distribution == 'Ubuntu' and ansible_distribution_version|int >= 20)
        or (ansible_distribution == 'Debian' and ansible_distribution_version|int >= 10)

    - name: GUI tools
      when: not is_wsl
      block:
        - name: Install meld (graphical tool to diff and merge files)
          package:
            name: meld

- name: Shellcheck
  hosts: all
  tags:
    - tools
    - shellcheck
  roles:
    - role: shellcheck
      tags: shellcheck
