---

- name: Install common Ubuntu applications and packages
  hosts: all
  tags:
  - ubuntu
  tasks:

  - name: Install Terminator
    package:
      name: terminator
    tags:
    - terminal
    when: not is_wsl

  - name: Add APT support for transport over HTTPS
    apt:
      name:
      - apt-transport-https
      - ca-certificates

  - name: Install software-properties-common
    apt:
      name: software-properties-common

- name: Install common Ubuntu applications and packages
  hosts: all
  tags: hyper
  roles:
  - role: markosamuli.hyper
    tags:
    - hyper
    when: not is_wsl
