---

- name: Install common Ubuntu applications and packages
  hosts: all
  tasks:
    
  - name: Install Terminator
    package:
      name: terminator

  - name: Add APT support for transport over HTTPS
    apt:
      name: '{{ item }}'
      state: present
    with_items:
    - apt-transport-https
    - ca-certificates     

  - name: Install software-properties-common     
    apt:
      name: software-properties-common
