---

- name: Visual Studio Code
  hosts: all
  tags:
    - vscode
    - frontend
    - editors
  tasks:
    - name: Remove tagplus5 Visual Studio Code PPA repository
      apt_repository:
        repo: 'deb https://tagplus5.github.io/vscode-ppa/ubuntu ./'
        state: absent

    - name: Remove Visual Studio Code if installed via APT
      apt:
        package: code
        state: absent

    - name: Check if vscode snap package exists
      stat:
        path: /snap/bin/vscode
      register: vscode_st
      changed_when: false

    - name: Remove unmaintained vscode snap package
      command: snap remove vscode
      when: vscode_st.stat.exists

    - name: Check if code snap package exists
      stat:
        path: /snap/bin/code
      register: code_st
      changed_when: false

    - name: Install Visual Studio Code if not running on WSL
      command: snap install code --classic
      when: not code_st.stat.exists and not is_wsl

    - name: Uninstall Visual Studio Code if running on WSL
      command: snap remove code
      when: code_st.stat.exists and is_wsl
